[project]
name = 'Collaborative-Fiction-Writing-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.contribution]
path = 'contracts/contribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty-distribution]
path = 'contracts/royalty-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.story]
path = 'contracts/story.clar'
clarity_version = 2
epoch = 2.5

[contracts.voting]
path = 'contracts/voting.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
